Repository google/clspv, pull requests merged in 2020-05, with the labels that each got.

#578 Fix local arg spec id assignment
  lib/AllocateDescriptorsPass.cpp
  lib/ArgKind.cpp
  lib/ArgKind.h
  lib/ClusterPodKernelArgumentsPass.cpp
  lib/Constants.h
  lib/SPIRVProducerPass.cpp
  test/multiple_local_ptr_args.cl
Labels: bug

#581 Fix check for module-scope push constants
  lib/Compiler.cpp
  test/PushConstant/pod_vs_module_scope.cl
Labels: bug

#584 Fix trunc removal in UndoTruncatedSwitchCondition
  lib/UndoTruncatedSwitchConditionPass.cpp
  test/widen_switch_condition_binary_ops.ll
  test/widen_switch_condition_trunc.ll
Labels: Mace Support, bug

#589 Update llvm
  deps.json
  lib/ZeroInitializeAllocasPass.cpp
  tools/clspv-opt/main.cpp
Labels: infrastructure

#595 Update LLVM
  deps.json
  test/hack_scf/greater_than_const_vec4.cl
Labels: infrastructure
