Repository google/clspv, pull requests merged in 2020-01, with the labels that each got.

#476 Add support for half image builtins
  lib/ReplaceOpenCLBuiltinPass.cpp
  test/ImageBuiltins/half_image_builtins.ll
Labels: enhancement

#479 Update LLVM
  deps.json
Labels: infrastructure

#470 Refactor checks about pointers in structs
  lib/FrontendPlugin.cpp
  test/Structs/kernel_arg_has_pointer_in_struct.cl
  test/Structs/mutual_recursion_error.cl
  test/Structs/ptr_in_struct.cl
  test/Structs/ptr_in_struct2.cl
Labels: bug

#471 Half float literal support
  lib/SPIRVProducerPass.cpp
  test/half-constants.cl
Labels: Mace Support, enhancement

#486 Update LLVM dep
  deps.json
Labels: infrastructure

#485 Fix loop merge and continue as same block
  amber/loops/split_merge_and_continue.amber
  include/clspv/Passes.h
  lib/CMakeLists.txt
  lib/Compiler.cpp
  lib/FixupStructuredCFGPass.cpp
  lib/Passes.cpp
  lib/Passes.h
  test/FixupStructuredCFG/multiple_inner_loop_phi_values.ll
  test/FixupStructuredCFG/single_block_inner_loop.ll
  test/FixupStructuredCFG/single_block_loop_phi.ll
  test/ProgramScopeConstants/select_between_constant_load.cl
  test/SamplerMap/TwoModuleScopeSamplers.cl
  test/for.cl
  test/hack_scf/const.ll
  test/hack_scf/const_left.ll
  test/hack_scf/const_vec2.ll
  test/hack_scf/greater_than_const.cl
  test/hack_scf/greater_than_const_left.cl
  test/hack_scf/greater_than_const_vec2.cl
  test/ifelse.cl
  test/ifelseif.cl
Labels: Mace Support, bug

#487 Truncate switch
  lib/UndoTruncatedSwitchConditionPass.cpp
  test/widen_switch_condition_binary_ops.ll
Labels: Mace Support, bug

#489 Update LLVM dep
  deps.json
Labels: infrastructure

#491 Support half variants of some builtins
  lib/SPIRVProducerPass.cpp
  lib/SplatArgPass.cpp
  test/CommonBuiltins/clamp/float2_clamp.cl
  test/CommonBuiltins/clamp/float3_clamp.cl
  test/CommonBuiltins/clamp/float4_clamp.cl
  test/CommonBuiltins/clamp/float_clamp.cl
  test/CommonBuiltins/clamp/half2_clamp.cl
  test/CommonBuiltins/clamp/half2_clamp_splat.ll
  test/CommonBuiltins/clamp/half3_clamp.cl
  test/CommonBuiltins/clamp/half3_clamp_splat.ll
  test/CommonBuiltins/clamp/half4_clamp.cl
  test/CommonBuiltins/clamp/half4_clamp_splat.ll
  test/CommonBuiltins/clamp/half_clamp.cl
  test/CommonBuiltins/max/float2_max.cl
  test/CommonBuiltins/max/float3_max.cl
  test/CommonBuiltins/max/float4_max.cl
  test/CommonBuiltins/max/float_max.cl
  test/CommonBuiltins/max/half2_fmax.cl
  test/CommonBuiltins/max/half2_fmax_splat.ll
  test/CommonBuiltins/max/half2_max.cl
  test/CommonBuiltins/max/half2_max_splat.ll
  test/CommonBuiltins/max/half3_fmax.cl
  test/CommonBuiltins/max/half3_fmax_splat.ll
  test/CommonBuiltins/max/half3_max.cl
  test/CommonBuiltins/max/half3_max_splat.ll
  test/CommonBuiltins/max/half4_fmax.cl
  test/CommonBuiltins/max/half4_fmax_splat.ll
  test/CommonBuiltins/max/half4_max.cl
  test/CommonBuiltins/max/half4_max_splat.ll
  test/CommonBuiltins/max/half_fmax.cl
  test/CommonBuiltins/max/half_max.cl
  test/CommonBuiltins/min/float2_min.cl
  test/CommonBuiltins/min/float3_min.cl
  test/CommonBuiltins/min/float4_min.cl
  test/CommonBuiltins/min/float_min.cl
  test/CommonBuiltins/min/half2_fmin.cl
  test/CommonBuiltins/min/half2_fmin_splat.ll
  test/CommonBuiltins/min/half2_min.cl
  test/CommonBuiltins/min/half2_min_splat.ll
  test/CommonBuiltins/min/half3_fmin.cl
  test/CommonBuiltins/min/half3_fmin_splat.ll
  test/CommonBuiltins/min/half3_min.cl
  test/CommonBuiltins/min/half3_min_splat.ll
  test/CommonBuiltins/min/half4_fmin.cl
  test/CommonBuiltins/min/half4_fmin_splat.ll
  test/CommonBuiltins/min/half4_min.cl
  test/CommonBuiltins/min/half4_min_splat.ll
  test/CommonBuiltins/min/half_fmin.cl
  test/CommonBuiltins/min/half_min.cl
  test/CommonBuiltins/mix/float2_mix.cl
  test/CommonBuiltins/mix/float3_mix.cl
  test/CommonBuiltins/mix/float4_mix.cl
  test/CommonBuiltins/mix/float_mix.cl
  test/CommonBuiltins/mix/half2_mix.cl
  test/CommonBuiltins/mix/half2_mix_splat.ll
  test/CommonBuiltins/mix/half3_mix.cl
  test/CommonBuiltins/mix/half3_mix_splat.ll
  test/CommonBuiltins/mix/half4_mix.cl
  test/CommonBuiltins/mix/half4_mix_splat.ll
  test/CommonBuiltins/mix/half_mix.cl
Labels: Mace Support, infrastructure

#492 Add sampler component masks to DescriptorMap.h
  include/clspv/DescriptorMap.h
  lib/DescriptorMap.cpp
Labels: enhancement

#499 Update LLVM
  deps.json
  lib/ClusterPodKernelArgumentsPass.cpp
  lib/InlineEntryPointsPass.cpp
  lib/InlineFuncWithPointerBitCastArgPass.cpp
  lib/InlineFuncWithPointerToFunctionArgPass.cpp
  lib/InlineFuncWithSingleCallSitePass.cpp
  lib/OpenCLInlinerPass.cpp
Labels: infrastructure

#498 Don't add int64 types due to literal operands
  lib/SPIRVProducerPass.cpp
  test/no_int64_due_to_index_literal.cl
Labels: Mace Support, enhancement

#501 Upgrade the GCC used in for Linux Kokoro bots
  kokoro/scripts/linux/build-amber.sh
  kokoro/scripts/linux/build-clvk.sh
  kokoro/scripts/linux/build.sh
Labels: infrastructure

#502 Update deps
  deps.json
  lib/Compiler.cpp
  lib/FrontendPlugin.cpp
  lib/ReplaceOpenCLBuiltinPass.cpp
  lib/SPIRVProducerPass.cpp
  lib/SpecializeImageTypes.cpp
Labels: infrastructure
