Repository google/clspv, pull requests merged in 2020-03, with the labels that each got.

#523 Update deps
  deps.json
  lib/Compiler.cpp
  lib/RemoveUnusedArguments.cpp
  test/RemoveUnusedArguments/remove_multiple_args.cl
  test/RemoveUnusedArguments/remove_multiple_args.ll
  test/clspv-opt/options.ll
Labels: infrastructure

#526 Update LLVM
  deps.json
  lib/ReplaceOpenCLBuiltinPass.cpp
  lib/SPIRVProducerPass.cpp
Labels: infrastructure

#533 Update LLVM
  deps.json
  lib/RewriteInsertsPass.cpp
  lib/SPIRVProducerPass.cpp
  lib/UBOTypeTransformPass.cpp
  tools/clspv-opt/main.cpp
Labels: infrastructure

#531 Builtins::Lookup interface - phase2
  lib/Builtins.cpp
  lib/Builtins.h
  lib/OpenCLInlinerPass.cpp
  lib/ReplaceOpenCLBuiltinPass.cpp
  lib/SPIRVProducerPass.cpp
  lib/SplatArgPass.cpp
Labels: enhancement

#534 Use unified1 version of spirv
  cmake/CMakeLists.txt
  cmake/spirv_c_strings.py
  lib/ReplaceLLVMIntrinsicsPass.cpp
  lib/ReplaceOpenCLBuiltinPass.cpp
  lib/SPIRVOp.h
  lib/SPIRVProducerPass.cpp
Labels: infrastructure

#539 Add attributes to functions pass
  deps.json
  include/clspv/Passes.h
  lib/AddFunctionAttributesPass.cpp
  lib/CMakeLists.txt
  lib/Compiler.cpp
  lib/Passes.cpp
  lib/Passes.h
  test/AddFunctionAttributes/no_sampler_phi.cl
  test/AddFunctionAttributes/translate_literal_sampler.ll
Labels: bug
