Repository google/clspv, pull requests merged in 2020-04, with the labels that each got.

#543 BugFix(#541): collect function list first, then replace usages with n…
  lib/SplatArgPass.cpp
Labels: bug

#546 Update dependencies
  deps.json
  lib/SPIRVProducerPass.cpp
Labels: infrastructure

#550 Add a new pass to undo harmful instcombines
  include/clspv/Passes.h
  lib/CMakeLists.txt
  lib/Compiler.cpp
  lib/Passes.cpp
  lib/Passes.h
  lib/UndoInstCombinePass.cpp
  test/UndoInstCombine/undo_extract_cast.cl
  test/UndoInstCombine/undo_extract_cast_2xi64_to_8xi16.ll
  test/UndoInstCombine/undo_extract_cast_4xi32_to_16xi8.ll
  test/UndoInstCombine/undo_shuffle_cast.cl
  test/UndoInstCombine/undo_shuffle_cast_2xi64_to_8xi16.ll
  test/UndoInstCombine/undo_shuffle_cast_4xi32_to16xi8.ll
Labels: bug

#548 Report all kernels in the descriptor map
  include/clspv/DescriptorMap.h
  lib/DescriptorMap.cpp
  lib/SPIRVProducerPass.cpp
  test/DirectResourceAccess/common_global_into_helper.cl
  test/ImageBuiltins/unsampled_read_image_descriptor_map.cl
  test/ProgramScopeConstants/constant_array_with_function_call_module_constants_storage_buffer.cl
  test/ProgramScopeConstants/in_storage_buffer_descriptor_map.cl
  test/ProgramScopeConstants/in_storage_buffer_descriptor_map_arr_arr.cl
  test/ProgramScopeConstants/in_storage_buffer_descriptor_map_arr_vec3.cl
  test/descriptor_set_default.cl
  test/descriptor_set_distinct.cl
  test/kernel-decl-dmap.cl
Labels: kokoro:run

#553 Update llvm
  deps.json
Labels: infrastructure

#556 Handle more instcombine vector casts
  lib/UndoInstCombinePass.cpp
  test/UndoInstCombine/extract_load_cast.cl
  test/UndoInstCombine/extract_load_cast_3xi32_to_6xi16.ll
  test/UndoInstCombine/extract_load_cast_inst_3xi32_to_6x16.ll
  test/UndoInstCombine/undo_shuffle_load_cast_3xi32_to_6xi16.ll
Labels: Mace Support, bug

#559 Add a pass to strip freeze instructions
  include/clspv/Passes.h
  lib/CMakeLists.txt
  lib/Compiler.cpp
  lib/Passes.cpp
  lib/Passes.h
  lib/StripFreezePass.cpp
  test/StripFreeze/strip_chain_freeze.ll
  test/StripFreeze/strip_multiple_uses.ll
  test/StripFreeze/strip_single_freeze.ll
Labels: Mace Support, enhancement

#561 Update LLVM
  deps.json
  lib/NormalizeGlobalVariable.cpp
  lib/ReplacePointerBitcastPass.cpp
  lib/RewriteInsertsPass.cpp
  lib/SPIRVProducerPass.cpp
  lib/UBOTypeTransformPass.cpp
Labels: infrastructure

#563 Update llvm
  deps.json
  lib/ClusterPodKernelArgumentsPass.cpp
  lib/InlineEntryPointsPass.cpp
  lib/InlineFuncWithPointerBitCastArgPass.cpp
  lib/InlineFuncWithPointerToFunctionArgPass.cpp
  lib/InlineFuncWithSingleCallSitePass.cpp
  lib/MultiVersionUBOFunctionsPass.cpp
  lib/OpenCLInlinerPass.cpp
  lib/ReplaceOpenCLBuiltinPass.cpp
  lib/UndoByvalPass.cpp
  lib/UndoSRetPass.cpp
Labels: infrastructure

#564 Update LLVM
  deps.json
  lib/UndoByvalPass.cpp
Labels: infrastructure

#569 Remove unused variables
  CMakeLists.txt
  kokoro/scripts/linux/build-amber.sh
  kokoro/scripts/linux/build-clvk.sh
  kokoro/scripts/linux/build.sh
  lib/AllocateDescriptorsPass.cpp
  lib/ComputeStructuredOrder.cpp
  lib/DefineOpenCLWorkItemBuiltinsPass.cpp
  lib/FrontendPlugin.cpp
  lib/MultiVersionUBOFunctionsPass.cpp
  lib/ReplaceLLVMIntrinsicsPass.cpp
  lib/ReplaceOpenCLBuiltinPass.cpp
  lib/ReplacePointerBitcastPass.cpp
  lib/RewriteInsertsPass.cpp
  lib/SignedCompareFixupPass.cpp
  lib/SplatArgPass.cpp
  test/WorkItemBuiltins/get_global_offset-push-constant-non-constant-dim.cl
Labels: bug, infrastructure

#570 Unify cmake handling for builds that use swiftshader
  kokoro/scripts/linux/build-amber.sh
  kokoro/scripts/linux/build-clvk.sh
Labels: infrastructure

#574 Update LLVM
  deps.json
  lib/UndoByvalPass.cpp
Labels: infrastructure
